# Generated by Django 3.2.11 on 2022-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default='exit', upload_to='images'),
            preserve_default=False,
        ),
    ]
